"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import YouTubeDownloader

# Implementing MyFrame1
class MyProject1MyFrame1( YouTubeDownloader.MyFrame1 ):
	def __init__( self, parent ):
		YouTubeDownloader.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def exitOnMenuSelection( self, event ):
		# TODO: Implement exitOnMenuSelection
		pass

	def aboutOnMenuSelection( self, event ):
		# TODO: Implement aboutOnMenuSelection
		pass

	def GetInfoOnButtonClick( self, event ):
		# TODO: Implement GetInfoOnButtonClick
		pass

	def SaveDirectoryOnButtonClick( self, event ):
		# TODO: Implement SaveDirectoryOnButtonClick
		pass

	def VideoOnRadioButton( self, event ):
		# TODO: Implement VideoOnRadioButton
		pass

	def AudioOnRadioButton( self, event ):
		# TODO: Implement AudioOnRadioButton
		pass

	def HighOnRadioButton( self, event ):
		# TODO: Implement HighOnRadioButton
		pass

	def MidiumOnRadioButton( self, event ):
		# TODO: Implement MidiumOnRadioButton
		pass

	def LowOnRadioButton( self, event ):
		# TODO: Implement LowOnRadioButton
		pass

	def SaveOnButtonClick( self, event ):
		# TODO: Implement SaveOnButtonClick
		pass

	def CancelOnButtonClick( self, event ):
		# TODO: Implement CancelOnButtonClick
		pass


